version: "3.7"

services:
  issuer-verifier-wallet-db:
    container_name: issuer-verifier-wallet-db
    image: ${POSTGRES_IMAGE}
    volumes:
      - issuer-verifier-wallet-db-volume:/var/lib/postgresql/data
    command: postgres -c 'max_connections=${MAX_CONNECTIONS_WALLET_DB}'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - von_von
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "50m"
    ports:
      - 5432:5432
    restart: always

networks:
  von_von:
    name: von_von

volumes:
  issuer-verifier-wallet-db-volume:
