version: "3.7"
services:
  tails-server:
    container_name: tails-server
    build:
      context: ./indy-tails-server
      dockerfile: docker/Dockerfile.tails-server
    command: >
      tails-server
        --host 0.0.0.0
        --port 6543
        --storage-path /tmp/tails-files
        --log-level INFO
    volumes:
      - tails-server-volume:/home/indy/tails-files
    ports:
      - 6543:6543
    networks:
      - aries-load-test
    restart: always

volumes:
  tails-server-volume:

networks:
  aries-load-test:
    external: true
    name: aries-load-test
